name: AmbServerPlugin
author: Mr_Amb
version: 1.1.0
main: amb.server.plugin.core.PluginCore
api-version: 1.16
commands:
  amb:
    description: AmbServer private command
    permission: amb
    permission-message: You not have permission to use this command.
    usage: "/amb permission <-u|-p> <add|del|get> [player] [permission]"